version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: cafe_ai_db
    environment:
      POSTGRES_DB: cafeaidb
      POSTGRES_USER: cafe
      POSTGRES_PASSWORD: 123456
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
    pgdata: